name: "Anti Virus - ClamAV"
on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"
    types:
      - "opened"
      - "edited"
      - "reopened"
      - "synchronize"
  schedule:
    - cron: "0 0 * * 3"
  workflow_dispatch:
jobs:
  anti-virus-clamav:
    name: "Anti Virus - ClamAV"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout Repository"
        uses: "actions/checkout@v2.3.4"
        with:
          fetch-depth: 0
      - name: "Checkout Pull Request"
        if: "${{github.event_name == 'pull_request'}}"
        run: "git checkout HEAD^2"
      - name: "Scan"
        uses: "djdefi/gitavscan@2"
        with:
          full: "--full"
